version: '3.8'

services:
  redis1:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis1data:/data
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  redis1data:
